### ISSUE TITLE
Can't disable write-proxy-v2

### ISSUE THREAD

**Issue by ThijsFeryn** [varnish/docker-hitch#1]
The new entrypoint approach for `docker-hitch` is very powerful, because it doesn't rely on environment variables.

However the `write-proxy-v2` cannot be disabled through command-line options. It is set to `on` in `hitch.conf`, but `--write-proxy-v2=off` is not allowed. 

Here's the error I got, when I tried it:

```
hitch: option '--write-proxy-v2' doesn't allow an argument
```
How are we going to tackle the issue? 

- Ask Dag to allow an `off` value on the command line? 
- Set it to `off` by default in `hitch.conf` on  `pkg-hitch`?

**Comment by gquintard** [comment]
this has been fixed I believe
