### ISSUE TITLE
Cannot pull image because of draconian rate limits by docker hub

### ISSUE THREAD

**Issue by ibotty** [varnish/docker-hitch#10]
This is basically the same issue as varnish/docker-varnish#52.

Please consider publishing to github's container registry or quay.io. Both have reasonable fair use policies at no cost.
```
> podman pull hitch
Trying to pull docker.io/library/hitch:latest...
WARN[0033] failed, retrying in 1s ... (1/3). Error: initializing source docker://hitch:latest: reading manifest latest in docker.io/library/hitch: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
[...]
```

**Comment by tianon** [comment]
FWIW, all the Docker Official Images are mirrored to Amazon's ECR Public: https://gallery.ecr.aws/docker/library/hitch

**Comment by gquintard** [comment]
Excellent, I didn't know that, thanks @tianon

**Comment by ibotty** [comment]
Thank you @tianon.  I did not know about ECR Public and its mirroring of `docker.io/library`.  That's good to know for other projects as well.
