### ISSUE TITLE
Require Linux/ARM64 docker image for varnish/hitch

### ISSUE THREAD

**Issue by odidev** [varnish/docker-hitch#7]
Hi Team, 

I have been working on build varnish/hitch images for both amd64 and arm64 platform. Successfully build the docker image for both the platform. I have modified the dockerfile to make it compatible for both arm64 and amd64. 

**Changes Required**: https://github.com/odidev/docker-hitch/commit/8fb790bb2632262ea6b162c98f0626e9e58877d9

Do you have any plans for releasing arm64 images? 

It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by gquintard** [comment]
Hi,

I think it make plenty of sense, fire away!

**Comment by gquintard** [comment]
Hi,
Can you report this one upstream please, and link the issue here?
